### PR TITLE
 work on v27 per instructions

### PR DESCRIPTION
**Pull request by paul-hammant**

### CODE REVIEW

**Comment by tolbertam** [comment]
Hi @paul-hammant , thanks for your contribution!  I think this change may not help your issue in jooby-project/jooby#1264 may not help as it looks like this project uses com.datastax.cassandra:cassandra-driver-core:3.5.0 and java-driver-shaded-cassandra is used only by com.datastax.oss:java-driver-core:4.0+ which is currently in beta.  The 4.x version of the java driver no longer has guava in its API, and it now shades guava per overwhelming request by the community.  Version 3.x must depend on a non-shaded version of guava because we have guava types in our public API.

Fortunately, cassandra-driver-core now supports Guava 16.0.1-26 as of version 3.6.0 ([JAVA-1928](https://datastax-oss.atlassian.net/browse/JAVA-1928)).  Since there appears to be no breaking changes in Guava 27, it may just be matter of upgrading your driver from 3.5.0 to 3.6.0 and things may just work.  I will run our test suite against Guava 27 soon to ensure 3.6.0 will work with it, but I suspect it should work fine.

**Comment by paul-hammant** [comment]
Breaking changes in v27 - https://github.com/google/guava/commit/87d87f5cac5a540d46a6382683722ead7b72d1b3 - removal of a deprecated method (to some) will be a break.

**Comment by tolbertam** [comment]
Ack, so I guess they are still removing stuff :(.   Fortunately in the 3.x driver I think we've isolated these changes they keep making to Futures code in [GuavaCompatbility](https://github.com/datastax/java-driver/blob/3.x/driver-core/src/main/java/com/datastax/driver/core/GuavaCompatibility.java) and we don't use any deprecated methods AFAIK in our Guava 19+ specific code.  I suspect at some point a future guava version will break something.  We just need to keep an eye on it and continue to support Guava 16.0.1+ as long as feasible.

**Comment by tolbertam** [comment]
I just ran our entire 3.x regression suite against Guava 27 and it ran well so I think we can safely assume Java Driver 3.6.0+ works with guava 27.

**Comment by adutra** [comment]
Closing as this artifact is not used by driver 3.x. Feel free to reopen if you disagree.

**Pull request closed without merging**
